name: Run Pyrogram Bot

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Bot
      env:
        API_ID: 1234567               # <-- apna API_ID yahan likho
        API_HASH: your_api_hash_here  # <-- apna API_HASH yahan likho
        BOT_TOKEN: your_bot_token_here # <-- apna BOT_TOKEN yahan likho
        ADMIN: 7409967984             # <-- apna Telegram User ID yahan likho
      run: python bot.py
